version: '3.1'
services:
  node:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./data:/usr/src/app/data
    restart: unless-stopped
    image: node:16
    container_name: bybit-websocket
    command: bash -c 'npm start'